---
kind: pipeline
type: docker
name: cran-latest

platform:
  os: linux
  arch: amd64

steps:
- name: pull
  image: omerxx/drone-ecr-auth
  commands:
  - $(aws ecr get-login --no-include-email --region us-east-1)
  - docker pull 906087756158.dkr.ecr.us-east-1.amazonaws.com/r-dev-ci-mpn-3.6:cran-latest
  - docker pull 906087756158.dkr.ecr.us-east-1.amazonaws.com/r-dev-ci-mpn-4.0:cran-latest
  - docker pull 906087756158.dkr.ecr.us-east-1.amazonaws.com/r-dev-ci-mpn-4.1:cran-latest
  volumes:
  - name: docker.sock
    path: /var/run/docker.sock

- name: "Check package: R 3.6"
  pull: never
  image: 906087756158.dkr.ecr.us-east-1.amazonaws.com/r-dev-ci-mpn-3.6:cran-latest
  commands:
  - R -s -e 'devtools::install_deps(upgrade = '"'"'always'"'"')'
  - R -s -e 'devtools::check(env_vars = c("NOT_CRAN" = "true"))'
  environment:
    USER: drone
  volumes:
  - name: cache
    path: /ephemeral

- name: "Check package: R 4.0"
  pull: never
  image: 906087756158.dkr.ecr.us-east-1.amazonaws.com/r-dev-ci-mpn-4.0:cran-latest
  commands:
  - R -s -e 'devtools::install_deps(upgrade = '"'"'always'"'"')'
  - R -s -e 'devtools::check(env_vars = c("NOT_CRAN" = "true"))'
  environment:
    USER: drone
  volumes:
  - name: cache
    path: /ephemeral

- name: "Check package: R 4.1"
  pull: never
  image: 906087756158.dkr.ecr.us-east-1.amazonaws.com/r-dev-ci-mpn-4.1:cran-latest
  commands:
  - R -s -e 'devtools::install_deps(upgrade = '"'"'always'"'"')'
  - R -s -e 'devtools::check(env_vars = c("NOT_CRAN" = "true"))'
  environment:
    USER: drone
  volumes:
  - name: cache
    path: /ephemeral

volumes:
- name: docker.sock
  host:
    path: /var/run/docker.sock
- name: cache
  temp: {}

trigger:
  event:
    exclude:
    - promote

---
kind: pipeline
type: docker
name: yspec-release

platform:
  os: linux
  arch: amd64

steps:
- name: pull
  image: omerxx/drone-ecr-auth
  commands:
  - $(aws ecr get-login --no-include-email --region us-east-1)
  - docker pull 906087756158.dkr.ecr.us-east-1.amazonaws.com/r-dev-ci-mpn-4.1:latest
  volumes:
  - name: docker.sock
    path: /var/run/docker.sock

- name: Build package
  pull: never
  image: 906087756158.dkr.ecr.us-east-1.amazonaws.com/r-dev-ci-mpn-4.1:latest
  commands:
  - git config --global user.email drone@metrumrg.com
  - git config --global user.name Drony
  - git fetch --tags
  - R -s -e 'devtools::install_deps(upgrade = '"'"'always'"'"')'
  - R -s -e 'pkgpub::create_tagged_repo(.dir = '"'"'/ephemeral'"'"')'
  volumes:
  - name: cache
    path: /ephemeral

- name: "Publish package: ${DRONE_TAG}"
  pull: if-not-exists
  image: plugins/s3
  settings:
    bucket: mpn.metworx.dev
    source: /ephemeral/${DRONE_TAG}/**/*
    strip_prefix: /ephemeral/${DRONE_TAG}/
    target: /releases/${DRONE_REPO_NAME}/${DRONE_TAG}
  volumes:
  - name: cache
    path: /ephemeral

- name: "Publish package: latest_tag"
  pull: if-not-exists
  image: plugins/s3
  settings:
    bucket: mpn.metworx.dev
    source: /ephemeral/${DRONE_TAG}/**/*
    strip_prefix: /ephemeral/${DRONE_TAG}/
    target: /releases/${DRONE_REPO_NAME}/latest_tag
  volumes:
  - name: cache
    path: /ephemeral

volumes:
- name: docker.sock
  host:
    path: /var/run/docker.sock
- name: cache
  temp: {}

trigger:
  event:
  - tag

depends_on:
- cran-latest