---
title: yspec yaml specification
---

- `about: [short-name, units]`
  - This is a convenience structure.
- `long: a longer name to describe the column`
- `range: [min-value, max-value]`
    - indicates continuous data
- `values: [val1, val2, valn]`
    - specify each valid value
    - indicates discrete data
- `values: {decode1: val1, decode22: val2}`
    - put the decode into the specification of values using a default 
      yaml map structure (the decode is to the left of the `:`)
    - __Note__ the curly brackets, not square brackets
- `decode: [decode1, decode2, decode3]`
    - Separate the `decode` from the `values` specification
    - See example below for clearer way to input very long decodes
- `longvalues: true`
    - print the values in a (long) `yaml`-formatted list
- `comment: just whatever you want to say`
- `comment: >
      say something
      on multiple lines of
      text`
- `source: ADSL.xpt`
    - Where the data came from
    - include both the sdtm domain and variable name
- `dots`: 
  - A named list of whatever you want to carry along in the object; the `dots` list
    isn't used by any rendering function in the yspec package, but might be used 
    by a custom rendering function 
- `axis`:
  - A short-ish name that can be used for axis titles for plots
  - Generally, don't include units; yspec helpers will add that 
    automatically by default
  - If `short` will work for your axis title (as it is ... with no 
    modification), yspec will use that if no `axis` field is used
- `type`:
  - Can be `numeric` or `character`
  - This is optional; the default is `character`
- `lookup`:
  - Logical; if `true` then the definition for the column is looked up in 
  the `lookup_files` (specificed in `SETUP__:`)
  - Use the `!look` handler to indicate lookup
  
## Examples

### Continuous values

- The `about` array provides a short name and units
- Any time `range` is given, the data is assumed to be continuous

```yaml
WT:
  about: [Weight, kg]
  range: [5,300]
```

This is equivalent to 

```yaml
WT:
  short: Weight
  units: kg
  range: [5,300]
```

### Character data
- Using `values` indicates discrete data

```yaml
RACE:
  values: [white, black, Native American, Other]
```

Any other array input structure can be used.  For example

```yaml
RACE: 
  values:
    - white
    - black
    - Native American
    - Other
```


By default, `values` are printed as comma-separated list.  To
get them to print in long format

```yaml
RACE:
  values: [white, black, Native American, Other]
  longvalues: true
```

### Integer data with decode

__Method 1__

- Notice that the yaml key can only be simple character value
- Also, we use curly braces to specify a list like this
- Finally it is a `:` that separates decode (on the left) and the 
  value (on the right).

```yaml
SEX:
  values: {dude: 0, gal: 1}
```

Special handlers are available that add some flexibility to this value / 
decode specification.  

The `!value:decode` handler allows you to put the value on the left and 
decode on the right

```yaml
SEX: 
  values: !value:decode
    - 0 : dude
    - 1 : gal
```

The default behavior can be achieved with

```yaml
SEX: 
  values: !value:decode
    - dude: 0
    - gal: 1
```

The handlers also allow associating multiple values with a single decode

__To get multiple values with the same decode__

```yaml
STUDY:
  values: !decode:value
    phase 1 : [101, 102, 103]
    phase 2 : [201, 202, 203]
    phase 3 : [301, 302, 303]
```


__Method 2__

- These are more complicated decodes
- Put the `values` and `deode` in brackets (array)

```yaml
BQL:
  values: [0,1]
  decode: [not below quantitation limit, below quantitation limit]
```

__Method 3__
Really, it's the same as method 2, but easier to type and read when the
decode gets really long

```yaml
BQL:
  values [0, 1]
  decode:
    - not below the quantitation limit of 2 ng/ml
    - below the quantitation limit of 2 ng/ml
```

### Look up column definition

Either fill in the `lookup` field or use the `!look` handler

```yaml
CMT: 
  lookup: true
```

```yaml
CMT: !look
```

