##' @importFrom yaml yaml.load_file as.yaml
##' @importFrom dplyr filter %>% bind_rows data_frame select_vars
##' @importFrom dplyr mutate if_else .data desc
##' @importFrom dplyr tibble
##' @importFrom rmarkdown render pdf_document html_document
##' @importFrom knitr kable
##' @importFrom xtable xtable
##' @importFrom utils capture.output head tail
##' @importFrom rlang quos set_names
##' @importFrom assertthat assert_that
##' @importFrom purrr map map_chr map_df map_if map_lgl
##' @importFrom purrr imap imap_chr
##' @importFrom purrr discard compact transpose
##' @importFrom purrr walk walk2 iwalk
##' @importFrom purrr flatten flatten_chr modify
##' @importFrom glue glue
##' @importFrom utils type.convert read.csv
##' 
##' @include utils.R
NULL

globalVariables(c("decode", "unit", "source", "type", "value"))

VALID_SPEC_NAMES <- c(
  "type", "unit", "values", "decode",
  "source", "comment",
  "short", "long", "about", "dots",
  "range", "longvalues", "lookup", 
  "axis", "table"
)

##' Demonstration object
##' 
##' @details
##' - `file` is the file name and path of a demonstration yspec file
##' - `spec()` is a function that generates a yspec object from `file`
##' - `data()` is a function that generates a data set that can be checked 
##'   against `spec()`
##' - `csv` is the file name (and path) to the data set generated by `data()`
##' - `proj()` is a function that generates a project object that can be 
##'   rendered into a document
##'   
##' @examples
##' spec <- ys_demo$spec()
##' 
##' ys_demo$file
##' 
##' dat <- ys_demo$data()  
##' 
##' @md
##' @export
ys_demo <- new.env()

.onLoad <- function(libname, pkgname) {
  file <- system.file("spec", "analysis1.yml", package = "yspec")
  ys_demo[["file"]] <- file
  ys_demo[["csv"]] <- system.file("internal", "analysis1.csv", package = "yspec")
  ys_demo[["spec"]] <- function() {
    ys_load(file)
  }
  ys_demo[["proj"]] <- function() {
    load_proj_ex("project.yml")
  }
  ys_demo[["data"]] <- function() {
    read.csv(
      file=ys_demo[["csv"]],
      na.strings = '.', as.is=TRUE, stringsAsFactors=FALSE
    )    
  }
}

