
##' View example workflow assets
##' 
##' This function copies files out of the yspec install directory and into 
##' the directory of your choosing.  
##' 
##' @param output the directory where assets should be copied
##' @param overwrite passed to [file.copy]
##' 
##' @details
##' - `analysis1.yml`: an example yaml file
##' - `analysis1.csv`: data set that works with `analysis1.yml`
##' - `ysdb_internal.yml`: the internal column lookup data base
##' - `ys_example.Rmd`: contains testing code that utilizes other assets
##' - `ys_get_assets.md`: a listing of assets that is exported
##' 
##' @examples
##' ys_get_assets("yspec_stuff")
##' 
##' 
##' @md
##' @export
ys_get_assets <- function(output,overwrite=FALSE) {
  output <- normalPath(output, mustWork=FALSE)
  if(!overwrite) {
    if(dir.exists(output)) {
      stop(
        "The output directory already exists; remove it or use ", 
        "overwrite=TRUE", call.=FALSE
      )
    }
  }
  if(!dir.exists(output)) dir.create(output)
  cp <- function(...) {
    file.copy(system.file(..., package = "yspec"), output, overwrite=overwrite)  
  }
  a <- cp("internal",  "analysis1.yml")
  b <- cp("internal",  "ysdb_internal.yml")
  c <- cp("internal",  "ys_get_assets.md")
  d <- cp("internal",  "analysis1.csv")
  e <- cp("internal",  "ys_example.Rmd")
  f <- cp("reference", "specification.md")
  if(!all(a,b,c,d,e)) {
    warning("Some assets were not exported.", call.=FALSE)  
  }
  return(invisible(output))
}


ys_view_impl <- function(dir,file) {
  file <- system.file(dir,file, package = "yspec")
  tmp <- file.path(tempdir(),paste0("view_",basename(file)))
  file.copy(file,tmp)
  if(requireNamespace("rstudioapi")) {
    rstudioapi::navigateToFile(tmp)
  } else {
    file.show(file)  
  }
}

ys_help_setup <- function(libname, pkgname) {
  file <- function() system.file("internal", "analysis1.yml", package = "yspec")
  csv  <- function() system.file("internal", "analysis1.csv", package = "yspec")
  spec <- function(...) ys_load(file(),...)
  proj <- function() load_proj_ex("project.yml")
  data <- function() {
    read.csv(
      file=csv(),
      na.strings = '.', as.is=TRUE, stringsAsFactors=FALSE
    )
  }
  specification <- function() {
    ys_view_impl("reference", "reference.md")  
  }
  internal_db <- function() {
    ys_view_impl("internal", "ysdb_internal.yml")    
  }
  analysis1 <- function() {
    ys_view_impl("internal", "analysis1.yml")  
  }
  ys_example <- function() {
    ys_view_impl("internal", "ys_example.Rmd") 
  }
  return(environment())
}

##' yspec help object
##' 
##' `ys_help` is an environment containing functions that can be called to 
##' provide information and examples for how yspec works.  `specification()`, 
##' `internal_db()` and `analysis1()` will open up markdown or yaml files
##' using [rstudioapi::navigateToFile] if that package is installed and 
##' [file.show] in case it is not.
##' 
##' @details
##' 
##' - `file()` the file name and path of an example yspec file
##' - `spec()` generates a yspec object from `file()`
##' - `data()` is a function that generates a data set that can be checked 
##'   against `spec()`
##' - `csv()` is the file name (and path) to the data set generated by `data()`
##' - `proj()` is a function that generates a project object that can be 
##'   rendered into a document
##' - `specification()` is a markdown document explaining what fields to include
##'   in the yaml specification
##' - `internal_db()` is the internal column lookup data base
##' - `analysis1()` is an example data specification file
##'
##' @examples
##' spec <- ys_help$spec()
##' 
##' file <- ys_help$file()
##' 
##' data <- ys_help$data()  
##' 
##' csv  <- ys_help$csv()
##' 
##' \dontrun{
##' proj <- ys_help$proj()
##' 
##' specif <- ys_help$specification()
##' 
##' inter <- ys_help$internal_db()
##' 
##' analysis1 <- ys_help$analysis1()
##' }
##' 
##' @md
##' @export
ys_help <- ys_help_setup()
